services:
  view-service:
    build:
      context: ./view-service
    expose:
      - 9000
    volumes:
      - ./view-service:/var/www
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - '8001:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./view-service:/var/www
    depends_on:
      - view-service
    restart: unless-stopped
