services:
  view-service:
    build:
      context: ./view-service
    expose:
      - 9000
    volumes:
      - ./view-service:/var/www
      - ./shared-data:/var/www/shared-data
    restart: unless-stopped

  upload-service:
    build:
      context: ./upload-service
    expose:
      - 9000
    volumes:
      - ./upload-service:/var/www
      - ./shared-data:/var/www/shared-data
    env_file:
      - ./upload-service/.env.local
    depends_on:
      - db
      - redis
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - '8001:81'
      - '8002:82'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./view-service:/var/www/view-service
      - ./upload-service:/var/www/upload-service
      - ./shared-data:/var/www/shared-data:ro
    depends_on:
      - view-service
      - upload-service
    restart: unless-stopped

  db:
    image: mysql:8.0
    env_file:
      - ./upload-service/.env.local
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3307:3306'
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - '5672:5672'
      - '15672:15672'
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  db:
  redis: