services:
  view-service:
    build:
      context: ./view-service
    expose:
      - 9000
    volumes:
      - ./view-service:/var/www/view-service
    restart: unless-stopped

  upload-service:
    build:
      context: ./upload-service
    expose:
      - 9001
    volumes:
      - ./upload-service:/var/www/upload-service
    env_file:
      - ./upload-service/.env.local
    depends_on:
      - db
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - '8001:81'
      - '8002:82'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./view-service:/var/www
    depends_on:
      - view-service
    restart: unless-stopped

  db:
    image: mysql:8.0
    env_file:
      - ./upload-service/.env.local
    volumes:
      - db:/var/lib/mysql
    ports:
      - '3307:3306'
    restart: unless-stopped

volumes:
  db:
